= API specification

RAID uses https://swagger.io/[Swagger,window=_blank] to implement the
https://swagger.io/specification/[OpenAPI Specification,window=_blank].

== Swagger UI

Perform the following steps to view the API via the Swagger UI:

1. Run the application locally by following the xref::install-and-run-quickstart.adoc[].
2. Go to http://localhost:8080/swagger-ui/index.html.

=== Run examples

The specification includes examples that can be run within the Swagger UI:

1. Click on an API endpoint to expand it.
2. Click *Try it out*.
3. Click *Execute* to run the prepopulated example.
4. Scroll down to view the response.

== Error codes

The specification includes the following error information:

1. The structure of the JSON error response, which is standardized across all endpoints
2. An example HTTP 400 response for each endpoint, where applicable due to the presence of input data
3. An example HTTP 500 response for each endpoint

See the table below for a full list of possible errors:

[%autowidth]
|===
|RAID error code|HTTP status code|Error message example|Zoo Chatbot|Handwriting recogniser

|001_MISSING_FIELD
|400 Bad Request
|Field 'message' is required
|image:green-tick.svg["Green tick",20]
|

|002_EMPTY_ARRAY
|400 Bad Request
|
|
|

|003_MISSING_IMAGE_FILE
|500 Internal Server Error
|
|
|

|100_UNKNOWN_ERROR
|500 Internal Server Error
|
|
|
|===



